version: '3.8'

services:
  api:
    build: 
      context: ./services/api
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./envs/.env.prod
    depends_on:
      - db
  bot:
    build: ./services/discord_bot
    command: python bot.py
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./envs/.env.prod.db
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - api

volumes:
  postgres_data_prod: