version: '3.8'

services:
  api:
    build: ./services/api
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/api/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
  bot:
    build: ./services/discord_bot
    command: python bot.py
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=discord_movie_bot
      - POSTGRES_PASSWORD=discord_movie_bot
      - POSTGRES_DB=discord_movie_bot_dev

volumes:
  postgres_data: